import { Trader, ChatMessage, LeaderboardEntry, CandleflipGame, CandleData } from './types';

export const mockTraders: Trader[] = [
  { id: '1', username: 'Zero2Hero', position: 1.477, pnl: 0.481, pnlPercentage: 19.32 },
  { id: '2', username: 'maydream', position: 0.017, pnl: 0.017, pnlPercentage: 6.36 },
  { id: '3', username: 'sheymann', position: 0.004, pnl: 0.004, pnlPercentage: 22.66 },
  { id: '4', username: 'jiabra', position: 0.003, pnl: 0.003, pnlPercentage: 19.92 },
  { id: '5', username: 'faibaker', position: 0.003, pnl: 0.003, pnlPercentage: 19.92 },
  { id: '6', username: 'gardiner', position: 0.002, pnl: 0.002, pnlPercentage: 19.92 },
  { id: '7', username: 'Teej', position: 0.001, pnl: 0.001, pnlPercentage: 11.82 },
  { id: '8', username: 'JKT123', position: 0.001, pnl: 0.001, pnlPercentage: 15.96 },
  { id: '9', username: 'kosmhard5', position: 0.000, pnl: 0.000, pnlPercentage: 18.23 },
  { id: '10', username: 'josefapra', position: 0.000, pnl: 0.000, pnlPercentage: 18.23 },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    userId: '1',
    username: 'Salmon',
    level: 78,
    message: "I'm making u bank",
    timestamp: new Date(),
    badges: ['VIP'],
  },
  {
    id: '2',
    userId: '2',
    username: 'Zyzco',
    level: 55,
    message: 'u under his ref?????',
    timestamp: new Date(),
    badges: ['MEMBER'],
  },
  {
    id: '3',
    userId: '3',
    username: 'MILKYBONGKID',
    level: 30,
    message: 'ahshha',
    timestamp: new Date(),
    badges: [],
  },
  {
    id: '4',
    userId: '4',
    username: 'Zero2Hero',
    level: 72,
    message: 'Candleflip big pull!',
    timestamp: new Date(),
    isAchievement: true,
    achievementData: {
      type: 'Candleflip',
      amount: 2.94,
    },
  },
  {
    id: '5',
    userId: '5',
    username: 'Bra22',
    level: 68,
    message: 'solomon send your wallet',
    timestamp: new Date(),
    badges: ['PARTNER'],
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, username: 'Demaux69', pnl: 56.95 },
  { rank: 2, username: 'Sneakzy', pnl: 33.57 },
  { rank: 3, username: 'RunTheJewels', pnl: 20.63 },
  { rank: 4, username: 'qTrades', pnl: 17.370 },
  { rank: 5, username: 'DontRugmeeee', pnl: 13.304 },
  { rank: 6, username: 'Anonymous', pnl: 13.114 },
  { rank: 7, username: 'Fannyman', pnl: 11.688 },
  { rank: 8, username: 'Solmon', pnl: 11.638 },
  { rank: 9, username: 'Tezzo', pnl: 9.996 },
  { rank: 10, username: 'GoingBankrupt', pnl: 9.667 },
  { rank: 11, username: 'charliekirk27', pnl: 9.506 },
  { rank: 12, username: 'GGMAX', pnl: 9.375 },
  { rank: 13, username: 'Rizz1', pnl: 9.049 },
  { rank: 14, username: 'Kingza', pnl: 7.706 },
  { rank: 15, username: 'Rushrewards', pnl: 7.676 },
  { rank: 16, username: 'imgoon2much', pnl: 7.349 },
  { rank: 17, username: 'Hazfkil', pnl: 6.972 },
  { rank: 18, username: 'faert', pnl: 6.025 },
  { rank: 19, username: 'KNULLA', pnl: 5.925 },
  { rank: 20, username: 'pina', pnl: 4.457 },
];

export const mockCandleflipGames: CandleflipGame[] = [
  {
    id: '1',
    status: 'completed',
    player1: { username: 'Bra22', bet: 0.2, side: 'bullish' },
    player2: { username: 'Jeff', bet: 0.2, side: 'bearish' },
    prize: 0.2,
    winner: 'player1',
  },
  {
    id: '2',
    status: 'completed',
    player1: { username: 'Bra22', bet: 0.098, side: 'bullish' },
    player2: { username: 'Jeff', bet: 0.1, side: 'bearish' },
    prize: 0.2,
    winner: 'player1',
  },
  {
    id: '3',
    status: 'active',
    player1: { username: 'Bra22', bet: 0.2, side: 'bullish' },
    player2: { username: 'Jeff', bet: 0.2, side: 'bearish' },
    prize: 0.2,
  },
  {
    id: '4',
    status: 'active',
    player1: { username: 'Bra22', bet: 0.2, side: 'bullish' },
    player2: { username: 'Jeff', bet: 0.2, side: 'bearish' },
    prize: 0.2,
  },
  {
    id: '5',
    status: 'completed',
    player1: { username: 'Jeff', bet: 0.2, side: 'bearish' },
    player2: { username: 'Bra22', bet: 0.2, side: 'bullish' },
    prize: 0.2,
    winner: 'player1',
  },
  {
    id: '6',
    status: 'completed',
    player1: { username: 'Jeff', bet: 0.2, side: 'bearish' },
    player2: { username: 'Bra22', bet: 0.2, side: 'bullish' },
    prize: 0.2,
    winner: 'player2',
  },
  {
    id: '7',
    status: 'completed',
    player1: { username: 'Jeff', bet: 0.2, side: 'bearish' },
    player2: { username: 'Bra22', bet: 0.2, side: 'bullish' },
    prize: 0.2,
    winner: 'player1',
  },
  {
    id: '8',
    status: 'completed',
    player1: { username: 'Jeff', bet: 0.2, side: 'bearish' },
    player2: { username: 'Bra22', bet: 0.2, side: 'bullish' },
    prize: 0.2,
    winner: 'player2',
  },
];

export const mockCandles: CandleData[] = [
  { open: 1, high: 1.5, low: 0.8, close: 1.3, timestamp: new Date(), multiplier: 1.3 },
  { open: 1.3, high: 1.8, low: 1.2, close: 1.6, timestamp: new Date(), multiplier: 1.6 },
  { open: 1.6, high: 1.7, low: 1.0, close: 1.2, timestamp: new Date(), multiplier: 1.2 },
  { open: 1.2, high: 1.5, low: 0.9, close: 0.8, timestamp: new Date(), multiplier: 0.8 },
  { open: 0.8, high: 1.0, low: 0.6, close: 0.7, timestamp: new Date(), multiplier: 0.7 },
  { open: 0.7, high: 1.2, low: 0.6, close: 1.0, timestamp: new Date(), multiplier: 1.0 },
  { open: 1.0, high: 1.6, low: 0.9, close: 1.4, timestamp: new Date(), multiplier: 1.4 },
  { open: 1.4, high: 2.0, low: 1.3, close: 1.8, timestamp: new Date(), multiplier: 1.8 },
  { open: 1.8, high: 2.2, low: 1.7, close: 2.0, timestamp: new Date(), multiplier: 2.0 },
  { open: 2.0, high: 2.5, low: 1.9, close: 1.5, timestamp: new Date(), multiplier: 1.5 },
  { open: 1.5, high: 1.7, low: 1.0, close: 1.2, timestamp: new Date(), multiplier: 1.2 },
  { open: 1.2, high: 1.5, low: 0.8, close: 1.477, timestamp: new Date(), multiplier: 1.477 },
];
